name: iOS Automated UI Tests

on:
  pull_request:
  workflow_dispatch:

jobs:

  iphone_14_pro_max:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: testing iPhone 14 Pro Max
        run: >-
          xcodebuild test -scheme testautomation -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro Max' -only-testing tests/UITest

  iphone_14_pro:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: testing iPhone 14 Pro
        run: >-
          xcodebuild test -scheme testautomation -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro' -only-testing tests/UITest

  iphone_14:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: testing iPhone 14
        run: >-
          xcodebuild test -scheme testautomation -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14' -only-testing tests/UITest
